// Augments the Cloudflare.Env namespace (generated by `wrangler types` into
// worker-configuration.d.ts) with the test-only binding injected via
// vitest.config.ts, so `env` from "cloudflare:test" is fully typed.
import type { D1Migration } from "@cloudflare/vitest-pool-workers";

declare global {
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}

export {};
